[build]
builder = "nixpacks"

[deploy]
preDeployCommand = ".venv/bin/python manage.py migrate"
startCommand = ".venv/bin/gunicorn --bind 0.0.0.0:$PORT outfits_garderobe.wsgi:application"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
