[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate && gunicorn outfits_garderobe.wsgi:application"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
