"""
Django settings for outfits_garderobe project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') + [
    'healthcheck.railway.app'
]

CSRF_TRUSTED_ORIGINS = [
    origin for origin in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if origin
]

# The session cookie is the only credential guarding every private photo behind
# the privatemedia gate, so it must never cross the wire in plaintext. Railway
# terminates TLS at its edge and forwards over HTTP, so Django needs the
# forwarded-proto header to know a request was secure — without it,
# SECURE_SSL_REDIRECT would loop.
#
# HSTS max-age is deliberately short. Browsers cache the header and a mistake
# cannot be recalled, only waited out — so it ships at one hour, pending
# verification in production. Raising it, and adding INCLUDE_SUBDOMAINS or
# PRELOAD, is a later and separate decision; PRELOAD in particular is close to
# permanent.
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # Railway's healthcheck calls /health/ over plain HTTP from inside its
    # network, with no forwarded-proto header. Redirected, it sees a 301, never
    # a 200, and fails the deploy — which is exactly what happened to deployment
    # a47ace49 on 2026-09-10. The endpoint returns a constant and sets no cookie.
    SECURE_REDIRECT_EXEMPT = [r'^health/$']
    SECURE_HSTS_SECONDS = 3600


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Account-only allauth: no 'allauth.socialaccount', and deliberately no
    # 'django.contrib.sites'/SITE_ID — allauth 65.x builds the absolute URLs it
    # mails from request.get_host() plus ACCOUNT_DEFAULT_HTTP_PROTOCOL instead.
    'allauth',
    'allauth.account',
    'anymail',
    'accounts',
    'privatemedia',
    'garments',
    'outfits',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Must come after AuthenticationMiddleware: it inspects request.user.
    'allauth.account.middleware.AccountMiddleware',
]

# ModelBackend stays first so /admin/ keeps working for accounts that predate
# allauth — that is the escape hatch which makes the production cutover in
# Phase 5 recoverable at every step.
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ROOT_URLCONF = 'outfits_garderobe.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # DIRS is searched before APP_DIRS, which is what lets templates/
        # override a template an installed app ships under the same name —
        # templates/allauth/layouts/base.html relies on exactly that.
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'outfits_garderobe.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Persistent connections. In production the app runs in europe-west4 and
# Postgres in sfo: a query round trip is ~150 ms and opening a connection
# ~1.1 s, which Django's default (a new connection per request) paid on every
# page and every photo tile. Measured 2026-09-13, see add-garment change.md.
#
# conn_max_age counts from when the connection was opened, not from its last
# use, so each gunicorn worker reconnects at most once every 5 minutes.
# conn_health_checks sends a SELECT 1 before a connection is reused in a new
# request — one extra round trip, but no 500 on the first request after Railway
# restarts Postgres for its scheduled updates. Moving Postgres to the app's
# region would shrink both costs; deliberately deferred until after the MVP.
DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=300,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Project-level static sources. This must never point at STATIC_ROOT:
# collectstatic would then read from and write to the same tree, hashing files
# it had already hashed. Sources live in static/, output goes to staticfiles/,
# and only the latter is gitignored.
STATICFILES_DIRS = [BASE_DIR / 'static']


# Uploaded files (private — served only through the privatemedia gate view)
# https://docs.djangoproject.com/en/6.0/ref/settings/#media-root
#
# MEDIA_ROOT must stay outside STATIC_ROOT and outside anything whitenoise
# serves. In production it points at a mounted volume; never add
# django.conf.urls.static.static() for it — that would serve uploads publicly.

# Outside DEBUG the mounted volume is mandatory and MEDIA_ROOT is required, the
# same way SECRET_KEY is: falling back to a path inside the image would send
# uploads to the container's ephemeral layer, which Railway destroys on the next
# deploy — losing user photos silently rather than failing at boot.
if DEBUG:
    MEDIA_ROOT = Path(os.getenv('MEDIA_ROOT', BASE_DIR / 'media'))
else:
    MEDIA_ROOT = Path(os.environ['MEDIA_ROOT'])

# Matches the gate's route prefix. ImageField.url is NOT the gate — it appends
# the storage name and resolves to nothing. Use PrivateImage.get_absolute_url().
MEDIA_URL = 'media/'

# A request-size ceiling checked before any upload is spooled to disk; see
# privatemedia/uploadhandlers.py. The other two are Django's defaults.
FILE_UPLOAD_HANDLERS = [
    'privatemedia.uploadhandlers.RequestSizeLimitUploadHandler',
    'django.core.files.uploadhandler.MemoryFileUploadHandler',
    'django.core.files.uploadhandler.TemporaryFileUploadHandler',
]


# Storage backends
# https://docs.djangoproject.com/en/6.0/ref/settings/#storages
#
# Django 5.1 removed STATICFILES_STORAGE; both keys below are mandatory.

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}


# Accounts (django-allauth)
# https://docs.allauth.org/en/latest/account/configuration.html
#
# Identity is the email address. The stock auth.User is kept rather than swapped
# — production already holds PrivateImage rows with a real FK to it — and the
# unique constraint that plain auth.User would have lacked on email comes from
# allauth's own account_emailaddress table. accounts.adapter writes the full
# address into User.username so the column stays populated and unique.

# These two must agree with each other; allauth's defaults are username-based
# ({'username'} and a list that includes 'username*'), which would put a field
# on the signup form that this product has no concept of.
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']

# A mistyped address is otherwise a silent lockout, discovered on the day
# password recovery is needed and not before.
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'

# Deliberate, not an oversight. allauth's default answers a signup for an
# existing address with a silent success — an anti-enumeration property. We
# trade it for a plain "already registered" error, because the alternative
# leaves a returning user staring at a confirmation email that never arrives.
# Note this also applies to password reset, which will likewise disclose
# whether an address has an account; 'strict' is the middle setting if that
# trade looks worse in practice than on paper.
ACCOUNT_PREVENT_ENUMERATION = False

# Where Django's authentication machinery sends people.
#
# LOGIN_URL is deliberately the *path*, not the 'account_login' route name:
# privatemedia/tests/test_gate.py:86 asserts the anonymous redirect's Location
# starts with settings.LOGIN_URL, which compares against a URL and would fail
# outright against a route name. The path is fixed by the 'accounts/' include
# prefix in outfits_garderobe/urls.py, which we control, so nothing is lost by
# hardcoding it — but change the two together or F-01's gate test breaks.
#
# Setting this at all is what repairs privatemedia/views.py:46: its
# @login_required has been redirecting to Django's /accounts/login/ default
# since F-01, a URL that did not exist until this change created it.
LOGIN_URL = '/accounts/login/'

# These two are route names on purpose. Login lands on the outfit grid — the
# `wardrobe` route, served by outfits.views since S-03 — as does `/` through
# accounts.views.home; the two must keep pointing at the same place.
LOGIN_REDIRECT_URL = 'wardrobe'
LOGOUT_REDIRECT_URL = 'account_login'

ACCOUNT_ADAPTER = 'accounts.adapter.AccountAdapter'
ACCOUNT_SIGNUP_FORM_CLASS = 'accounts.forms.SignupForm'

# ACCOUNT_SESSION_REMEMBER is deliberately unset: its default of None means
# "ask the user", which is what renders the login form's "Remember me?"
# checkbox. Unchecked, allauth ends the session when the browser closes;
# checked, the session lives for SESSION_COOKIE_AGE below.
#
# Two weeks is a trade. Someone standing at their wardrobe with a phone should
# not have to re-authenticate on every visit — but that same cookie is the only
# credential guarding every private photo, so a stolen or forgotten-on-a-shared-
# device session stays useful for this long. SESSION_EXPIRE_AT_BROWSER_CLOSE
# stays at its default; allauth sets expiry per login from the checkbox.
SESSION_COOKIE_AGE = 60 * 60 * 24 * 14

# With no sites framework, allauth composes the links it mails from this plus
# request.get_host(). Left at its 'http' default, every confirmation and reset
# link would bounce off SECURE_SSL_REDIRECT on click — and once HSTS is cached,
# some browsers refuse the http:// link outright.
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'http' if DEBUG else 'https'


# Email
# https://anymail.dev/en/stable/esps/brevo/
#
# Under DEBUG, confirmation and reset links are printed to the console; an unset
# EMAIL_BACKEND would default to SMTP on localhost:25, which fails silently and
# makes mandatory verification look broken.
#
# Production sends through Brevo's HTTP API, not its SMTP relay: Railway blocks
# outbound SMTP on the Hobby plan this project runs on
# (https://docs.railway.com/networking/outbound-networking), so
# smtp-relay.brevo.com is unreachable from the container. The key must be a v3
# API key (xkeysib-…), and DEFAULT_FROM_EMAIL must match a verified Brevo sender
# character for character — Brevo rejects anything else.
#
# Both are read with no fallback, like SECRET_KEY and MEDIA_ROOT: a missing value
# should stop the boot, not run degraded and silently lose every reset link.
# The 10-second timeout replaces anymail's 30, so a Brevo outage becomes an
# error page rather than a hung signup form.
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'Outfits Garderobe <noreply@localhost>')
else:
    EMAIL_BACKEND = 'anymail.backends.brevo.EmailBackend'
    ANYMAIL = {
        'BREVO_API_KEY': os.environ['BREVO_API_KEY'],
        'REQUESTS_TIMEOUT': 10,
    }
    DEFAULT_FROM_EMAIL = os.environ['DEFAULT_FROM_EMAIL']
