# Generated by Django 6.0.5 on 2026-09-05 21:06

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import privatemedia.models
import privatemedia.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateImage',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        upload_to=privatemedia.models.upload_to_uuid,
                        validators=[privatemedia.validators.validate_max_size],
                    ),
                ),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='private_images',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [
                    models.Index(
                        fields=['owner', '-uploaded_at'], name='privatemedi_owner_i_bcb18e_idx'
                    )
                ],
            },
        ),
    ]
