# Generated by Django 6.0.5 on 2026-09-09 22:01

import django.core.validators
from django.db import migrations, models

import privatemedia.models
import privatemedia.validators


class Migration(migrations.Migration):
    dependencies = [
        ('privatemedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateimage',
            name='image',
            field=models.ImageField(
                upload_to=privatemedia.models.upload_to_uuid,
                validators=[
                    privatemedia.validators.validate_max_size,
                    django.core.validators.validate_image_file_extension,
                ],
            ),
        ),
    ]
