# Generated by Django 6.0.8 on 2026-09-13 09:58

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('privatemedia', '0002_alter_privateimage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Garment',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('tshirt', 'T-shirt'),
                            ('shirt', 'Shirt'),
                            ('sweater', 'Sweater'),
                            ('outerwear', 'Jacket / coat'),
                            ('trousers', 'Trousers'),
                            ('shorts', 'Shorts'),
                            ('skirt', 'Skirt'),
                            ('dress', 'Dress'),
                            ('shoes', 'Shoes'),
                            ('accessory', 'Accessory'),
                            ('other', 'Other'),
                        ],
                        max_length=20,
                    ),
                ),
                ('type_other', models.CharField(blank=True, max_length=40)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='garments',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'photo',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name='garment',
                        to='privatemedia.privateimage',
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(
                        fields=['owner', '-created_at'], name='garments_ga_owner_i_8ab3a5_idx'
                    )
                ],
                'constraints': [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ('type', 'other'), models.Q(('type_other', ''), _negated=True)
                            ),
                            models.Q(
                                models.Q(('type', 'other'), _negated=True), ('type_other', '')
                            ),
                            _connector='OR',
                        ),
                        name='garment_type_other_matches_type',
                        violation_error_message='Only the Other type carries custom text.',
                    )
                ],
            },
        ),
    ]
