# Generated by Django 6.0.8 on 2026-09-13 15:47

import uuid

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('garments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Outfit',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('name', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('garments', models.ManyToManyField(related_name='outfits', to='garments.garment')),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='outfits',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(
                        fields=['owner', '-created_at'], name='outfits_out_owner_i_ff288c_idx'
                    )
                ],
                'constraints': [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower('name'),
                        models.F('owner'),
                        name='outfit_name_unique_per_owner',
                        violation_error_message='You already have an outfit with this name.',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(('name', ''), _negated=True),
                        name='outfit_name_not_empty',
                        violation_error_message='An outfit needs a name.',
                    ),
                ],
            },
        ),
    ]
