# Generated by Django 6.0.8 on 2026-09-13 21:09

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('outfits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('name', models.CharField(max_length=30)),
                ('normalized', models.CharField(blank=True, editable=False, max_length=90)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='tags',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['normalized'],
            },
        ),
        migrations.AddField(
            model_name='outfit',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='outfits', to='outfits.tag'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(
                fields=('owner', 'normalized'),
                name='tag_unique_per_owner',
                violation_error_message='You already have this tag.',
            ),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.CheckConstraint(
                condition=models.Q(('normalized', ''), _negated=True),
                name='tag_name_not_empty',
                violation_error_message='A tag needs a name.',
            ),
        ),
    ]
