# Generated by Django 6.0.8 on 2026-09-14 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('outfits', '0002_tag'),
        ('privatemedia', '0002_alter_privateimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='photo',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name='outfit',
                to='privatemedia.privateimage',
            ),
        ),
    ]
