# Generated by Django 6.0.8 on 2026-09-14 12:03

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('outfits', '0003_outfit_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingGarment',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('tshirt', 'T-shirt'),
                            ('shirt', 'Shirt'),
                            ('sweater', 'Sweater'),
                            ('outerwear', 'Jacket / coat'),
                            ('trousers', 'Trousers'),
                            ('shorts', 'Shorts'),
                            ('skirt', 'Skirt'),
                            ('dress', 'Dress'),
                            ('shoes', 'Shoes'),
                            ('accessory', 'Accessory'),
                            ('other', 'Other'),
                        ],
                        max_length=20,
                    ),
                ),
                ('type_other', models.CharField(blank=True, max_length=40)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('removed_at', models.DateTimeField(auto_now_add=True)),
                (
                    'outfit',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='missing_garments',
                        to='outfits.outfit',
                    ),
                ),
            ],
            options={
                'ordering': ['removed_at'],
            },
        ),
    ]
